<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>fastapi on dullmode</title>
    <link>https://dullmode.github.io/tags/fastapi/</link>
    <description>Recent content in fastapi on dullmode</description>
    <image>
      <title>dullmode</title>
      <url>https://imgur.com/a/SR2UQt7</url>
      <link>https://imgur.com/a/SR2UQt7</link>
    </image>
    <generator>Hugo -- gohugo.io</generator>
    <language>ja-jp</language>
    <lastBuildDate>Tue, 18 Oct 2022 16:49:15 +0900</lastBuildDate><atom:link href="https://dullmode.github.io/tags/fastapi/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>fastapiとstaticFile()でmethod not allowed</title>
      <link>https://dullmode.github.io/posts/2022-10-18/</link>
      <pubDate>Tue, 18 Oct 2022 16:49:15 +0900</pubDate>
      
      <guid>https://dullmode.github.io/posts/2022-10-18/</guid>
      <description>エラー staticFileマウントしたらなんかPOSTできなかった
import os from fastapi import FastAPI from fastapi.staticfiles import StaticFiles from pydantic import BaseModel class Chat(BaseModel): text: str app = FastAPI() this_directory = os.path.dirname(__file__) app.mount(&amp;#34;/&amp;#34;, StaticFiles(directory=os.path.join(this_directory, &amp;#34;static&amp;#34;), html=True), name=&amp;#34;static&amp;#34;) @app.post(&amp;#34;/chat/&amp;#34;) async def create_item(chat: Chat): return chat 127.0.0.1:46940 - &amp;#34;POST /chat/ HTTP/1.1&amp;#34; 405 Method Not Allowed 解決 app.mount()をルーターより後におけば大丈夫になった
import os from fastapi import FastAPI from fastapi.staticfiles import StaticFiles from pydantic import BaseModel class Chat(BaseModel): text: str app = FastAPI() # この部分をmountより前に @app.</description>
    </item>
    
    <item>
      <title>jinja2.exceptions.TemplateNotFoundの解決</title>
      <link>https://dullmode.github.io/posts/2022-04-15/</link>
      <pubDate>Fri, 15 Apr 2022 16:51:35 +0900</pubDate>
      
      <guid>https://dullmode.github.io/posts/2022-04-15/</guid>
      <description>大丈夫なパターン htmlファイルのあるフォルダと関数Jinja2Templatesを呼び出すpythonファイルが同一階層の場合は出現しません。
testapp ├ app.py └ templates └ index.html from fastapi import FastAPI from fastapi.templating import Jinja2Templates from fastapi.responses import HTMLResponse from fastapi.requests import Request app = FastAPI() templates = Jinja2Templates(directory=&amp;#39;templates&amp;#39;) @app.get(&amp;#34;/&amp;#34;, response_class=HTMLResponse) def index(request:Request): return templates.TemplateResponse( &amp;#34;index.html&amp;#34;, {&amp;#34;request&amp;#34;: request) ) エラーが出るパターン htmlファイルのあるフォルダと関数Jinja2Templatesを呼び出すpythonファイルが同一階層に無い場合にエラーが出現します。
testapp ├ router │ └ route.py ├ templates │ └ index.html └ main.py from fastapi import FastAPI from .router import route app = FastAPI() app.include_router(route.router) from fastapi import APIRouter from fastapi.</description>
    </item>
    
    <item>
      <title>fastapi&#43;uvicornでInvalid HTTP request received</title>
      <link>https://dullmode.github.io/posts/2022-03-22/</link>
      <pubDate>Tue, 22 Mar 2022 14:55:31 +0900</pubDate>
      
      <guid>https://dullmode.github.io/posts/2022-03-22/</guid>
      <description>invalid HTTP request received 本番環境でfastapiを動かしている時に以下のエラーが出力されました。
INFO: Started server process [9806] INFO: Waiting for application startup. INFO: Application startup complete. INFO: Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit) WARNING: Invalid HTTP request received. Traceback (most recent call last): File &amp;#34;/home/ec2-user/.local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py&amp;#34;, line 170, in handle_events event = self.conn.next_event() File &amp;#34;/home/ec2-user/.local/lib/python3.7/site-packages/h11/_connection.py&amp;#34;, line 443, in next_event exc._reraise_as_remote_protocol_error() File &amp;#34;/home/ec2-user/.local/lib/python3.7/site-packages/h11/_util.py&amp;#34;, line 76, in _reraise_as_remote_protocol_error raise self File &amp;#34;/home/ec2-user/.local/lib/python3.7/site-packages/h11/_connection.py&amp;#34;, line 425, in next_event event = self.</description>
    </item>
    
  </channel>
</rss>
